name: Npm Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      # caching
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-
          restore-keys: |
            ${{ runner.os }}-npm-
      - run: yarn
      - run: ultra -r --serial --rebuild --filter '@vitro/*' build
      - run: yarn jest tests/fixtures.test.ts --colors
      - run: git -c color.ui=always diff
      # - name: Bump version
      #   if: github.ref == 'refs/heads/master'
      #   uses: remorses/bump-version@js
      #   with:
      #     version_file: ./VERSION
      #     prerelease_tag: alpha
      #     ignore: dist, esm, .next
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - run: yarn lerna publish -c patch
      #   env:
      #       NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
